version: '3'
services:
  politik-bei-uns-oparl:
    container_name: politik-bei-uns-oparl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    volumes:
      - .:/app
    entrypoint: ["python3", "runserver.py"]
    networks:
      shared_politk-bei-uns:
        aliases:
          - oparl

networks:
  shared_politk-bei-uns:
    external: true